<?php
/**
 * ContactApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Planfix REST API
 *
 * Documentation for Planfix REST API. <br> Generated <a href=\"https://root/restapidocs/swagger.json\">swagger.json</a>
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ContactApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContactApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getContactById
     *
     * Get contact by number.
     *
     */
    public function testGetContactById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getContactComments
     *
     * Get list of comments added to contact.
     *
     */
    public function testGetContactComments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getContactFiles
     *
     * Get contact files.
     *
     */
    public function testGetContactFiles()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getContactList
     *
     * Get list of contacts and companies.
     *
     */
    public function testGetContactList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getContactListGroups
     *
     * Get list of contact groups.
     *
     */
    public function testGetContactListGroups()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getContactListTemplates
     *
     * Get list of contact or company templates.
     *
     */
    public function testGetContactListTemplates()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postContact
     *
     * Create contact or company.
     *
     */
    public function testPostContact()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postContactAddComment
     *
     * Add comment.
     *
     */
    public function testPostContactAddComment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postContactAddDataTagEntryExistingComment
     *
     * Add a data tag entry to an existing comment.
     *
     */
    public function testPostContactAddDataTagEntryExistingComment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postContactAddDataTagEntryNewComment
     *
     * Add a data tag entry with a new comment.
     *
     */
    public function testPostContactAddDataTagEntryNewComment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postContactById
     *
     * Update contact by number.
     *
     */
    public function testPostContactById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postContactFilters
     *
     * Get list contact filters.
     *
     */
    public function testPostContactFilters()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postContactImport
     *
     * Import contact list.
     *
     */
    public function testPostContactImport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postContactUpdateComment
     *
     * Update comment.
     *
     */
    public function testPostContactUpdateComment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
