<?php
/**
 * CustomFieldsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Planfix REST API
 *
 * Documentation for Planfix REST API. <br> Generated <a href=\"https://root/restapidocs/swagger.json\">swagger.json</a>
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomFieldsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomFieldsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCustomfieldContact
     *
     * Get a list of a custom contact fields.
     *
     */
    public function testGetCustomfieldContact()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomfieldGeneric
     *
     * Get list of custom main fields.
     *
     */
    public function testGetCustomfieldGeneric()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomfieldProject
     *
     * Get a list of custom project fields.
     *
     */
    public function testGetCustomfieldProject()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomfieldTask
     *
     * Get list of custom task fields.
     *
     */
    public function testGetCustomfieldTask()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomfieldUser
     *
     * Get list of custom employee fields.
     *
     */
    public function testGetCustomfieldUser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomfieldsForContact
     *
     * Get a list of a custom fields for contact.
     *
     */
    public function testGetCustomfieldsForContact()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomfieldsForDatatag
     *
     * Get list of custom fields for data tag.
     *
     */
    public function testGetCustomfieldsForDatatag()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomfieldsForDirectory
     *
     * Get list of custom fields for directory.
     *
     */
    public function testGetCustomfieldsForDirectory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomfieldsForProject
     *
     * Get list of custom fields for project.
     *
     */
    public function testGetCustomfieldsForProject()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomfieldsForTask
     *
     * Get list of custom fields for task.
     *
     */
    public function testGetCustomfieldsForTask()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomfieldsForUser
     *
     * Get list of custom fields for employee.
     *
     */
    public function testGetCustomfieldsForUser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
