<?php
/**
 * TaskApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Planfix REST API
 *
 * Documentation for Planfix REST API. <br> Generated <a href=\"https://root/restapidocs/swagger.json\">swagger.json</a>
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TaskApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TaskApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getTaskById
     *
     * Get task by number.
     *
     */
    public function testGetTaskById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTaskComments
     *
     * Get task comments.
     *
     */
    public function testGetTaskComments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTaskFiles
     *
     * Get task files.
     *
     */
    public function testGetTaskFiles()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTaskList
     *
     * Get list of tasks.
     *
     */
    public function testGetTaskList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTaskListTemplates
     *
     * Get list of task templates.
     *
     */
    public function testGetTaskListTemplates()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postTask
     *
     * Create task.
     *
     */
    public function testPostTask()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postTaskAddComment
     *
     * Add comment.
     *
     */
    public function testPostTaskAddComment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postTaskAddDataTagEntryExistingComment
     *
     * Add a data tag entry to an existing comment.
     *
     */
    public function testPostTaskAddDataTagEntryExistingComment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postTaskAddDataTagEntryNewComment
     *
     * Add data tag entry as new comment.
     *
     */
    public function testPostTaskAddDataTagEntryNewComment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postTaskById
     *
     * Update task by number.
     *
     */
    public function testPostTaskById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postTaskFilters
     *
     * Get list task filters.
     *
     */
    public function testPostTaskFilters()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postTaskUpdateComment
     *
     * Updating comments.
     *
     */
    public function testPostTaskUpdateComment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
